[workspace]
members = [
    "client",
    "server", "shared",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
